project:
  type: website

website:
  site-url: https://iqb-vocabs.github.io/p18/
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-vocabs/p18/
  navbar:
    logo: iqb-logo-black.png
    search: true
    left:
      - href: index.qmd
        text: "Metadatenprofile für Testaufgaben: Deutsch HSA 2004"
    right:
      - icon: github
        href: https://github.com/iqb-vocabs/p18
        aria-label: Source Code

lang: de

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
